// Copyright Woogle. All Rights Reserved.

//
// BP 그래프 → 의사 코드 렌더러.
//
// 접근 방식:
//   - Entry 노드(Event / CustomEvent / FunctionEntry)에서 시작해 exec 체인을 따라간다.
//   - 각 exec 노드는 RenderExecNode 안의 TryRender* 디스패처가 노드 타입에 맞는 라인을 찍는다.
//   - 데이터 입력 핀은 RenderDataInput → RenderExpression 재귀로 역방향 평가.
//   - UK2Node_Knot은 데이터/실행 양쪽 모두 SkipKnots로 pass-through.
//   - exec cycle은 Visited set으로 감지해 goto 라인으로 처리. 데이터 핀 재귀는 깊이 제한(MaxExpressionDepth)으로 차단.
//   - 알려지지 않은 노드 타입은 RenderFallbackNode가 NodeTitle 한 줄로 기록 — 회귀는 조용히 발생할 수 있음.
//

#include "WxBlueprintSnapshotExporter.h"
#include "Engine/Blueprint.h"
#include "EdGraph/EdGraph.h"
#include "EdGraph/EdGraphNode.h"
#include "EdGraph/EdGraphPin.h"
#include "EdGraphSchema_K2.h"
#include "K2Node.h"
#include "K2Node_Event.h"
#include "K2Node_CustomEvent.h"
#include "K2Node_FunctionEntry.h"
#include "K2Node_FunctionResult.h"
#include "K2Node_CallFunction.h"
#include "K2Node_VariableGet.h"
#include "K2Node_VariableSet.h"
#include "K2Node_IfThenElse.h"
#include "K2Node_ExecutionSequence.h"
#include "K2Node_MacroInstance.h"
#include "K2Node_Knot.h"
#include "K2Node_Self.h"
#include "K2Node_Literal.h"
#include "K2Node_DynamicCast.h"
#include "Dom/JsonObject.h"
#include "Dom/JsonValue.h"

namespace
{
	// 데이터 핀 사이클(드물지만 매크로/커스텀 노드에서 가능)에서의 무한 재귀 방지.
	constexpr int32 MaxExpressionDepth = 32;

	struct FPseudoLine
	{
		int32 Indent = 0;
		FString Text;
	};

	struct FPseudoEntry
	{
		FString Header;
		TArray<FPseudoLine> Body;
	};

	struct FRenderCtx
	{
		TArray<FPseudoLine>& Body;
		TSet<UEdGraphNode*>& Visited;
		int32 ExprDepth = 0; // 데이터 핀 표현식 재귀 깊이; TGuardValue로 자동 증감
	};

	UEdGraphPin* SkipKnots(UEdGraphPin* Pin);
	FString RenderExpression(UEdGraphPin* OutputPin, FRenderCtx& Ctx);
	FString RenderDataInput(UEdGraphPin* InputPin, FRenderCtx& Ctx);
	void RenderExecChain(UEdGraphPin* ExecOutPin, int32 Indent, FRenderCtx& Ctx);
	void RenderExecNode(UEdGraphNode* Node, int32 Indent, FRenderCtx& Ctx);

	void Emit(FRenderCtx& Ctx, int32 Indent, FString Text)
	{
		Ctx.Body.Add({ Indent, MoveTemp(Text) });
	}

	bool IsExecPin(const UEdGraphPin* Pin)
	{
		return Pin && Pin->PinType.PinCategory == UEdGraphSchema_K2::PC_Exec;
	}

	UEdGraphPin* FindThenPin(UEdGraphNode* Node)
	{
		if (!Node)
		{
			return nullptr;
		}
		for (UEdGraphPin* Pin : Node->Pins)
		{
			if (Pin && Pin->Direction == EGPD_Output && IsExecPin(Pin))
			{
				return Pin;
			}
		}
		return nullptr;
	}

	UEdGraphPin* SkipKnots(UEdGraphPin* Pin)
	{
		if (!Pin)
		{
			return nullptr;
		}
		while (Pin && Cast<UK2Node_Knot>(Pin->GetOwningNode()))
		{
			UK2Node_Knot* Knot = Cast<UK2Node_Knot>(Pin->GetOwningNode());
			UEdGraphPin* Upstream = Pin->Direction == EGPD_Input ? Knot->GetInputPin() : Knot->GetOutputPin();
			if (!Upstream || Upstream->LinkedTo.Num() == 0)
			{
				return nullptr;
			}
			Pin = Upstream->LinkedTo[0];
		}
		return Pin;
	}

	FString FormatLiteralPin(const UEdGraphPin* Pin)
	{
		if (!Pin)
		{
			return TEXT("?");
		}
		if (Pin->DefaultObject)
		{
			return Pin->DefaultObject->GetName();
		}
		const FString Val = Pin->DefaultValue.IsEmpty() ? Pin->AutogeneratedDefaultValue : Pin->DefaultValue;
		if (Val.IsEmpty())
		{
			if (Pin->PinType.PinCategory == UEdGraphSchema_K2::PC_Object
				|| Pin->PinType.PinCategory == UEdGraphSchema_K2::PC_Class
				|| Pin->PinType.PinCategory == UEdGraphSchema_K2::PC_Interface
				|| Pin->PinType.PinCategory == UEdGraphSchema_K2::PC_SoftObject
				|| Pin->PinType.PinCategory == UEdGraphSchema_K2::PC_SoftClass)
			{
				return TEXT("None");
			}
			return TEXT("");
		}
		if (Pin->PinType.PinCategory == UEdGraphSchema_K2::PC_String
			|| Pin->PinType.PinCategory == UEdGraphSchema_K2::PC_Text
			|| Pin->PinType.PinCategory == UEdGraphSchema_K2::PC_Name)
		{
			return FString::Printf(TEXT("\"%s\""), *Val);
		}
		return Val;
	}

	FString RenderDataInput(UEdGraphPin* InputPin, FRenderCtx& Ctx)
	{
		if (!InputPin)
		{
			return TEXT("?");
		}
		if (InputPin->LinkedTo.Num() == 0)
		{
			return FormatLiteralPin(InputPin);
		}
		UEdGraphPin* Src = SkipKnots(InputPin->LinkedTo[0]);
		if (!Src)
		{
			return FormatLiteralPin(InputPin);
		}
		return RenderExpression(Src, Ctx);
	}

	FString RenderCallArgs(UK2Node_CallFunction* Call, FRenderCtx& Ctx)
	{
		TArray<FString> Args;
		for (UEdGraphPin* Pin : Call->Pins)
		{
			if (!Pin || Pin->Direction != EGPD_Input || IsExecPin(Pin))
			{
				continue;
			}
			if (Pin->PinName == UEdGraphSchema_K2::PN_Self)
			{
				continue;
			}
			// 숨김 핀(WorldContextObject 등)은 사용자가 건드리지 않으면 스킵
			if (Pin->bHidden && Pin->LinkedTo.Num() == 0)
			{
				continue;
			}
			// 연결도 없고 기본값이 autogenerated 그대로면 스킵 (Duration, Key, bPrintToScreen 등)
			if (Pin->LinkedTo.Num() == 0 && Pin->DefaultValue == Pin->AutogeneratedDefaultValue)
			{
				continue;
			}
			Args.Add(FString::Printf(TEXT("%s=%s"), *Pin->PinName.ToString(), *RenderDataInput(Pin, Ctx)));
		}
		return FString::Join(Args, TEXT(", "));
	}

	FString RenderCallTarget(UK2Node_CallFunction* Call, FRenderCtx& Ctx)
	{
		UEdGraphPin* SelfPin = Call->FindPin(UEdGraphSchema_K2::PN_Self);
		if (SelfPin && SelfPin->LinkedTo.Num() > 0)
		{
			return RenderDataInput(SelfPin, Ctx) + TEXT(".");
		}
		if (Call->FunctionReference.IsSelfContext())
		{
			return FString();
		}
		if (UClass* MemberClass = Call->FunctionReference.GetMemberParentClass())
		{
			return MemberClass->GetName() + TEXT("::");
		}
		return FString();
	}

	FString RenderExpression(UEdGraphPin* OutputPin, FRenderCtx& Ctx)
	{
		if (!OutputPin)
		{
			return TEXT("?");
		}
		if (Ctx.ExprDepth >= MaxExpressionDepth)
		{
			return TEXT("...");
		}
		TGuardValue<int32> DepthGuard(Ctx.ExprDepth, Ctx.ExprDepth + 1);

		UEdGraphNode* Node = OutputPin->GetOwningNode();
		if (!Node)
		{
			return TEXT("?");
		}

		if (Cast<UK2Node_Self>(Node))
		{
			return TEXT("Self");
		}
		if (UK2Node_VariableGet* VG = Cast<UK2Node_VariableGet>(Node))
		{
			return VG->GetVarNameString();
		}
		if (UK2Node_Literal* Lit = Cast<UK2Node_Literal>(Node))
		{
			if (UObject* Obj = Lit->GetObjectRef())
			{
				return Obj->GetName();
			}
			return Lit->GetNodeTitle(ENodeTitleType::ListView).ToString();
		}
		if (UK2Node_CallFunction* Call = Cast<UK2Node_CallFunction>(Node))
		{
			const FString Target = RenderCallTarget(Call, Ctx);
			const FString FnName = Call->GetFunctionName().ToString();
			const FString Args = RenderCallArgs(Call, Ctx);
			FString Expr = FString::Printf(TEXT("%s%s(%s)"), *Target, *FnName, *Args);
			if (OutputPin->PinName != UEdGraphSchema_K2::PN_ReturnValue && !OutputPin->PinName.IsNone())
			{
				Expr += FString::Printf(TEXT(".%s"), *OutputPin->PinName.ToString());
			}
			return Expr;
		}
		if (UK2Node_DynamicCast* DCast = Cast<UK2Node_DynamicCast>(Node))
		{
			UEdGraphPin* ObjIn = DCast->GetCastSourcePin();
			const FString TypeName = DCast->TargetType ? DCast->TargetType->GetName() : TEXT("?");
			return FString::Printf(TEXT("Cast<%s>(%s)"), *TypeName, *RenderDataInput(ObjIn, Ctx));
		}

		// 일반 K2Node fallback: NodeTitle + 필요시 출력 핀명
		FString Title = Node->GetNodeTitle(ENodeTitleType::ListView).ToString();
		Title.ReplaceInline(TEXT("\n"), TEXT(" "));
		if (!OutputPin->PinName.IsNone() && OutputPin->PinName != UEdGraphSchema_K2::PN_ReturnValue)
		{
			return FString::Printf(TEXT("%s.%s"), *Title, *OutputPin->PinName.ToString());
		}
		return Title;
	}

	void RenderExecChain(UEdGraphPin* ExecOutPin, int32 Indent, FRenderCtx& Ctx)
	{
		if (!ExecOutPin || ExecOutPin->LinkedTo.Num() == 0)
		{
			return;
		}
		UEdGraphPin* NextPin = SkipKnots(ExecOutPin->LinkedTo[0]);
		if (!NextPin)
		{
			return;
		}
		UEdGraphNode* NextNode = NextPin->GetOwningNode();
		if (!NextNode)
		{
			return;
		}
		if (Ctx.Visited.Contains(NextNode))
		{
			Emit(Ctx, Indent, FString::Printf(TEXT("goto %s"), *NextNode->GetName()));
			return;
		}
		Ctx.Visited.Add(NextNode);
		RenderExecNode(NextNode, Indent, Ctx);
	}

	bool TryRenderBranch(UEdGraphNode* Node, int32 Indent, FRenderCtx& Ctx)
	{
		UK2Node_IfThenElse* Branch = Cast<UK2Node_IfThenElse>(Node);
		if (!Branch)
		{
			return false;
		}
		Emit(Ctx, Indent, FString::Printf(TEXT("if (%s):"), *RenderDataInput(Branch->GetConditionPin(), Ctx)));
		RenderExecChain(Branch->GetThenPin(), Indent + 1, Ctx);
		UEdGraphPin* ElsePin = Branch->GetElsePin();
		if (ElsePin && ElsePin->LinkedTo.Num() > 0)
		{
			Emit(Ctx, Indent, TEXT("else:"));
			RenderExecChain(ElsePin, Indent + 1, Ctx);
		}
		return true;
	}

	bool TryRenderSequence(UEdGraphNode* Node, int32 Indent, FRenderCtx& Ctx)
	{
		UK2Node_ExecutionSequence* Seq = Cast<UK2Node_ExecutionSequence>(Node);
		if (!Seq)
		{
			return false;
		}
		int32 Idx = 0;
		for (UEdGraphPin* Pin : Seq->Pins)
		{
			if (Pin && Pin->Direction == EGPD_Output && IsExecPin(Pin))
			{
				Emit(Ctx, Indent, FString::Printf(TEXT("# sequence[%d]"), Idx++));
				RenderExecChain(Pin, Indent, Ctx);
			}
		}
		return true;
	}

	bool TryRenderVariableSet(UEdGraphNode* Node, int32 Indent, FRenderCtx& Ctx)
	{
		UK2Node_VariableSet* VS = Cast<UK2Node_VariableSet>(Node);
		if (!VS)
		{
			return false;
		}
		UEdGraphPin* ValPin = VS->FindPin(VS->GetVarName());
		Emit(Ctx, Indent, FString::Printf(TEXT("%s = %s"), *VS->GetVarNameString(), *RenderDataInput(ValPin, Ctx)));
		RenderExecChain(FindThenPin(VS), Indent, Ctx);
		return true;
	}

	bool TryRenderCallFunction(UEdGraphNode* Node, int32 Indent, FRenderCtx& Ctx)
	{
		UK2Node_CallFunction* Call = Cast<UK2Node_CallFunction>(Node);
		if (!Call)
		{
			return false;
		}
		Emit(Ctx, Indent, FString::Printf(TEXT("%s%s(%s)"),
			*RenderCallTarget(Call, Ctx), *Call->GetFunctionName().ToString(), *RenderCallArgs(Call, Ctx)));
		RenderExecChain(FindThenPin(Call), Indent, Ctx);
		return true;
	}

	bool TryRenderDynamicCast(UEdGraphNode* Node, int32 Indent, FRenderCtx& Ctx)
	{
		UK2Node_DynamicCast* DCast = Cast<UK2Node_DynamicCast>(Node);
		if (!DCast)
		{
			return false;
		}
		const FString TypeName = DCast->TargetType ? DCast->TargetType->GetName() : TEXT("?");
		Emit(Ctx, Indent, FString::Printf(TEXT("As%s = Cast<%s>(%s)"), *TypeName, *TypeName, *RenderDataInput(DCast->GetCastSourcePin(), Ctx)));
		UEdGraphPin* Success = DCast->GetValidCastPin();
		UEdGraphPin* Failed = DCast->GetInvalidCastPin();
		if (Success && Success->LinkedTo.Num() > 0)
		{
			Emit(Ctx, Indent, FString::Printf(TEXT("if (As%s):"), *TypeName));
			RenderExecChain(Success, Indent + 1, Ctx);
		}
		if (Failed && Failed->LinkedTo.Num() > 0)
		{
			Emit(Ctx, Indent, TEXT("else:"));
			RenderExecChain(Failed, Indent + 1, Ctx);
		}
		return true;
	}

	bool TryRenderMacro(UEdGraphNode* Node, int32 Indent, FRenderCtx& Ctx)
	{
		UK2Node_MacroInstance* Macro = Cast<UK2Node_MacroInstance>(Node);
		if (!Macro)
		{
			return false;
		}
		UEdGraph* MacroGraph = Macro->GetMacroGraph();
		const FString MacroName = MacroGraph ? MacroGraph->GetName() : TEXT("Macro");

		TArray<FString> Args;
		for (UEdGraphPin* Pin : Macro->Pins)
		{
			if (Pin && Pin->Direction == EGPD_Input && !IsExecPin(Pin))
			{
				Args.Add(FString::Printf(TEXT("%s=%s"), *Pin->PinName.ToString(), *RenderDataInput(Pin, Ctx)));
			}
		}

		UEdGraphPin* LoopBody = Macro->FindPin(TEXT("LoopBody"));
		UEdGraphPin* Completed = Macro->FindPin(TEXT("Completed"));
		if (LoopBody || Completed)
		{
			Emit(Ctx, Indent, FString::Printf(TEXT("%s(%s):"), *MacroName, *FString::Join(Args, TEXT(", "))));
			if (LoopBody)
			{
				RenderExecChain(LoopBody, Indent + 1, Ctx);
			}
			if (Completed)
			{
				RenderExecChain(Completed, Indent, Ctx);
			}
			return true;
		}

		Emit(Ctx, Indent, FString::Printf(TEXT("%s(%s)"), *MacroName, *FString::Join(Args, TEXT(", "))));
		RenderExecChain(FindThenPin(Macro), Indent, Ctx);
		return true;
	}

	bool TryRenderReturn(UEdGraphNode* Node, int32 Indent, FRenderCtx& Ctx)
	{
		UK2Node_FunctionResult* Ret = Cast<UK2Node_FunctionResult>(Node);
		if (!Ret)
		{
			return false;
		}
		TArray<FString> Returns;
		for (UEdGraphPin* Pin : Ret->Pins)
		{
			if (Pin && Pin->Direction == EGPD_Input && !IsExecPin(Pin))
			{
				Returns.Add(FString::Printf(TEXT("%s=%s"), *Pin->PinName.ToString(), *RenderDataInput(Pin, Ctx)));
			}
		}
		Emit(Ctx, Indent, FString::Printf(TEXT("return %s"), *FString::Join(Returns, TEXT(", "))));
		return true;
	}

	void RenderFallbackNode(UEdGraphNode* Node, int32 Indent, FRenderCtx& Ctx)
	{
		FString Title = Node->GetNodeTitle(ENodeTitleType::ListView).ToString();
		Title.ReplaceInline(TEXT("\n"), TEXT(" "));
		Emit(Ctx, Indent, Title);
		RenderExecChain(FindThenPin(Node), Indent, Ctx);
	}

	void RenderExecNode(UEdGraphNode* Node, int32 Indent, FRenderCtx& Ctx)
	{
		if (TryRenderBranch(Node, Indent, Ctx))
		{
			return;
		}
		if (TryRenderSequence(Node, Indent, Ctx))
		{
			return;
		}
		if (TryRenderVariableSet(Node, Indent, Ctx))
		{
			return;
		}
		if (TryRenderCallFunction(Node, Indent, Ctx))
		{
			return;
		}
		if (TryRenderDynamicCast(Node, Indent, Ctx))
		{
			return;
		}
		if (TryRenderMacro(Node, Indent, Ctx))
		{
			return;
		}
		if (TryRenderReturn(Node, Indent, Ctx))
		{
			return;
		}
		RenderFallbackNode(Node, Indent, Ctx);
	}

	bool BuildEntryHeader(UEdGraphNode* Entry, FString& OutHeader)
	{
		if (UK2Node_CustomEvent* Ce = Cast<UK2Node_CustomEvent>(Entry))
		{
			OutHeader = FString::Printf(TEXT("custom_event %s:"), *Ce->CustomFunctionName.ToString());
			return true;
		}
		if (UK2Node_Event* Ev = Cast<UK2Node_Event>(Entry))
		{
			OutHeader = FString::Printf(TEXT("event %s:"), *Ev->EventReference.GetMemberName().ToString());
			return true;
		}
		if (UK2Node_FunctionEntry* Fe = Cast<UK2Node_FunctionEntry>(Entry))
		{
			TArray<FString> Params;
			for (UEdGraphPin* Pin : Fe->Pins)
			{
				if (Pin && Pin->Direction == EGPD_Output && !IsExecPin(Pin))
				{
					Params.Add(Pin->PinName.ToString());
				}
			}
			const FName FnName = Fe->CustomGeneratedFunctionName.IsNone()
				? Fe->FunctionReference.GetMemberName()
				: Fe->CustomGeneratedFunctionName;
			OutHeader = FString::Printf(TEXT("function %s(%s):"), *FnName.ToString(), *FString::Join(Params, TEXT(", ")));
			return true;
		}
		return false;
	}

	bool RenderEntryNode(UEdGraphNode* Entry, FPseudoEntry& OutEntry)
	{
		if (!BuildEntryHeader(Entry, OutEntry.Header))
		{
			return false;
		}
		TSet<UEdGraphNode*> Visited;
		Visited.Add(Entry);
		FRenderCtx Ctx{ OutEntry.Body, Visited };
		RenderExecChain(FindThenPin(Entry), 1, Ctx);
		return true;
	}

	TArray<FPseudoEntry> RenderGraphPseudoCode(UEdGraph* Graph)
	{
		TArray<FPseudoEntry> Entries;
		if (!Graph)
		{
			return Entries;
		}

		TArray<UEdGraphNode*> EntryNodes;
		for (UEdGraphNode* Node : Graph->Nodes)
		{
			if (Node && (Cast<UK2Node_Event>(Node) || Cast<UK2Node_CustomEvent>(Node) || Cast<UK2Node_FunctionEntry>(Node)))
			{
				EntryNodes.Add(Node);
			}
		}

		EntryNodes.Sort([](UEdGraphNode& A, UEdGraphNode& B)
		{
			return A.GetNodeTitle(ENodeTitleType::ListView).ToString() < B.GetNodeTitle(ENodeTitleType::ListView).ToString();
		});

		for (UEdGraphNode* Node : EntryNodes)
		{
			FPseudoEntry Entry;
			if (RenderEntryNode(Node, Entry) && Entry.Body.Num() > 0)
			{
				Entries.Add(MoveTemp(Entry));
			}
		}
		return Entries;
	}

	void EmitGraphJson(UEdGraph* Graph, TSharedPtr<FJsonObject> Root)
	{
		TArray<FPseudoEntry> Entries = RenderGraphPseudoCode(Graph);
		if (Entries.Num() == 0)
		{
			return;
		}

		TArray<TSharedPtr<FJsonValue>> LineValues;
		for (const FPseudoEntry& Entry : Entries)
		{
			LineValues.Add(MakeShared<FJsonValueString>(Entry.Header));
			for (const FPseudoLine& Line : Entry.Body)
			{
				const FString Pad = FString::ChrN(Line.Indent * 2, TEXT(' '));
				LineValues.Add(MakeShared<FJsonValueString>(Pad + Line.Text));
			}
		}
		Root->SetArrayField(Graph->GetName(), LineValues);
	}
}

TSharedPtr<FJsonObject> FWxBlueprintSnapshotExporter::BuildGraphsJson(UBlueprint* Blueprint)
{
	if (!Blueprint)
	{
		return nullptr;
	}

	TSharedPtr<FJsonObject> Root = MakeShared<FJsonObject>();

	for (UEdGraph* Graph : Blueprint->UbergraphPages)
	{
		EmitGraphJson(Graph, Root);
	}
	for (UEdGraph* Graph : Blueprint->FunctionGraphs)
	{
		EmitGraphJson(Graph, Root);
	}

	return Root;
}
